### ISSUE TITLE
question: i would like to know why `trial` didn't use the `package-inferred-system` extension provided by asdf.

### ISSUE THREAD

**Issue by sakurawald** [Shirakumo/trial#100]
Hello, i see there are `trial.asd` file and `package.lisp` file in the root directory of `trial project`.
I would like to know the reason, why `trial` didn't use the `package-inferred-system` extension provided by asdf, while you are making the design decisions.

Thank you~

**Comment by Shinmera** [comment]
Package inferred systems are a bad idea in every case, imo.

Packages define the interface for the user of a library. The files and the system define the organisational structure for the maintainers. They are different levels of organisation that have almost nothing in common with one-another.

In addition, package-inferred-systems require you to create additional packages to define dependence relations between files, which in turn makes symbol sharing a nightmare in bigger projects, or they lead you to create gigantic monolithic files, which makes maintenance hard because you can no longer logically divide parts up in files as you please.

**Comment by sakurawald** [comment]
Okay, thank you!

**Comment by sakurawald** [comment]
I found that `trial` use lots of `(in-package #:org.shirakumo.fraf.trial)` to put all symbols inside a main package, keeping a simple logical structure, while leaving a modular physical structure (i mean the .lisp source files in file system). Is this the right?

**Comment by Shinmera** [comment]
I suppose you could say that, yes. The core of trial is mostly all contained in one package. Extension systems, such as the various context backends, audio output, different file formats, and so on, do use separate packages though.

**Comment by sakurawald** [comment]
> I found that `trial` use lots of `(in-package #:org.shirakumo.fraf.trial)` to put all symbols inside a main package, keeping a simple logical structure, while leaving a modular physical structure (i mean the .lisp source files in file system). Is this the right?

I also found that this makes the usage of `(defmethod ...)` much easier, since all the `class` are defined in one main package.

**Comment by sakurawald** [comment]
Yeah, if a `class` is defined in its own `package`, then each time a `sub-class` must change the package to `(defmethod ...)` for its super-class, this is verbose.
Is this one of the reasons you choose to use one big package ?

**Comment by sakurawald** [comment]
> Yeah, if a `class` is defined in its own `package`, then each time a `sub-class` must change the package to `(defmethod ...)` for its super-class (or using package prefix for the symbol), this is verbose. Is this one of the reasons you choose to use one big package ?

**Comment by Shinmera** [comment]
I can't say that was actually one of the considerations; as I mentioned, classes and symbol organisation are largely unrelated.

It just "makes intuitive sense" to me to use a big package for a big system like Trial. It makes development a lot easier not to have to worry about symbol sharing all the time.

**Comment by sakurawald** [comment]
Thank you for your answer.

**Comment by Shinmera** [comment]
Sure. Sorry I can't provide clearer insight!
