### ISSUE TITLE
cl+trial not defined at compile time

### ISSUE THREAD

**Issue by atgreen** [Shirakumo/trial#102]
The current package.lisp conditionally defines the :cl+trial package.  However, this package is not available at compile-time when we are trying to reference it a little later.

debugger invoked on a PACKAGE-DOES-NOT-EXIST in thread
#<THREAD tid=3430084 "main thread" RUNNING {100DFC8003}>:
  The name "CL+TRIAL" does not designate any package.

Consider wrapping this defpackage in an eval-when.

```
(eval-when (:compile-toplevel :load-toplevel :execute)
  (unless (find-package :cl+trial)
    (defpackage :cl+trial
      (:nicknames #:org.shirakumo.fraf.trial.cl+trial)
      (:shadowing-import-from #:trial #:// #:load #:random)
      (:use #:cl
            #:trial
            #:org.shirakumo.fraf.math))))
```

**Comment by Shinmera** [comment]
In general I catch issues like this in due time. Reporting stuff for errors present on git master isn't too helpful. The dist exists for a reason.
