### ISSUE TITLE
vertex-attrib-array-offset not defined

### ISSUE THREAD

**Issue by atgreen** [Shirakumo/trial#103]
Does trial depend on cl-opengl code that hasn't been published yet?

```
;   Error during compiler-macroexpansion of
;   (CFFI:CONVERT-TO-FOREIGN :VERTEX-ATTRIB-ARRAY-OFFSET 'CL-OPENGL-BINDINGS:ENUM).
;   Use *BREAK-ON-SIGNALS* to intercept.
;   
;    :VERTEX-ATTRIB-ARRAY-OFFSET is not defined as a keyword for enum type #<CFFI::FOREIGN-ENUM CL-OPENGL-BINDINGS:ENUM>.

```

**Comment by Shinmera** [comment]
Works on my machine. Please use the dist and ensure your software is updated.

**Comment by 3b** [comment]
i don't see that defined by cl-opengl, and don't see "GL_VERTEX_ATTRIB_ARRAY_OFFSET" in GL docs, but https://github.com/Shirakumo/trial/blob/master/resources/vertex-array.lisp#L40 is using it. Not sure if differences in build method hide it sometimes?
