### ISSUE TITLE
Shirakumo dist version doesn't compile

### ISSUE THREAD

**Issue by hpoggie** [Shirakumo/trial#104]
Attempting to `(ql:quickload :trial)` (with the Shirakumo dist installed) gives this error:
```
debugger invoked on a SB-PCL:CLASS-NOT-FOUND-ERROR in thread
#<THREAD tid=534534 "main thread" RUNNING {10003E8143}>:
  There is no class named TRIAL::ATRIGGER-VOLUME.
```

The string `atrigger-volume` doesn't seem to appear anywhere in git history, so I guess the typo must have been introduced locally somehow? Anyway, using the source from github fixes it.

**Comment by Shinmera** [comment]
Sorry about that, seems I pushed a bad commit and did a dist recompile before ammending the fix. Should be good now.

**Comment by hpoggie** [comment]
I'm now hitting this when I try to quickload:
```
Unknown CFFI type EVENT-TYPE
   [Condition of type CFFI::UNDEFINED-FOREIGN-TYPE-ERROR]
```

Seems like this is a cl-gamepad thing. Should I open an issue on there?

**Comment by Shinmera** [comment]
cl-gamepad hasn't changed in forever. Make sure you're loading from a clean slate.

**Comment by hpoggie** [comment]
OK, yeah, it works after removing and reinstalling quicklisp. Thanks!
