### ISSUE TITLE
Impractical filenames in editor/data/icons/

### ISSUE THREAD

**Issue by metayan** [Shirakumo/trial#14]
If SBCL is run without UTF-8 support, the files
```
editor/data/icons/mouse-↑-window 4.svg
editor/data/icons/mouse-↑-window 5.svg
```
cause access to `editor/data/icons/` to fail:
```
CL-USER[1]: (directory #P"editor/data/icons/")
(#P"/trial/editor/data/icons/")
CL-USER[2]: (directory #P"editor/data/icons/*.*")
debugger invoked on a SB-INT:C-STRING-DECODING-ERROR in thread
#<THREAD "main thread" RUNNING {1001930083}>:
  :ASCII c-string decoding error: the octet sequence #(226) cannot be decoded.

(SB-IMPL::READ-FROM-C-STRING/ASCII #.(SB-SYS:INT-SAP #X038010DD) CHARACTER)
```

The directory is scanned during `(ql:register-local-projects)`, so it can get quite messy...

One solution is to run SBCL with
```
LC_CTYPE=en_US.UTF-8 sbcl
```

Maybe it is Quicklisp that should handle this in a nicer way, so filed an issue there too:
https://github.com/quicklisp/quicklisp-client/issues/152

**Comment by Shinmera** [comment]
While I could easily change these files' names, I do not support unicode-less systems anyway.
