### ISSUE TITLE
Getting Started? Tutorial? Readme?

### ISSUE THREAD

**Issue by Borderliner** [Shirakumo/trial#21]
It would be great if `trial` provides newcomers with some getting started material. There isn't even a readme file explaining what the project is, how to install, etc.

**Comment by Shinmera** [comment]
Thanks for the request!

Installing should just be a matter of cloning and loading, much like every other lisp project. I'm not sure that documenting things beyond that is a great idea because the project is very much in flux still, and I'm wary of spending my already stripped time on writing docs for things that might get scrapped again anyway, instead of fixing bugs and adding things.

There's a bunch of video material covering aspects of the engine though, which you can find on youtube. Particularly the following two study sessions:
https://www.youtube.com/watch?v=0v6iv_3BLeo
https://www.youtube.com/watch?v=jaJRGWY94k0
Though the first one is outdated in a few aspects. Then there's also the ongoing "treehouse" series:
https://www.youtube.com/playlist?list=PLkDl6Irujx9MtJPRRP5KBH40SGCenztPW
Which covers Trial sometimes by practical use, sometimes by internal development.

**Comment by Shinmera** [comment]
People are also more than welcome to join the #shirakumo IRC channel on Freenode to ask questions directly.

**Comment by Borderliner** [comment]
I see. Documenting is of course not an easy job. But how about auto-generated documentation, much like what Doxygen does? Is such a thing possible? This way, you don't have to put much extra effort organizing a manual, and you can integrate it into the code as well.

**Comment by Shinmera** [comment]
Just having a symbol index with no documentation wouldn't be of any use.

**Comment by Borderliner** [comment]
Not symbol index. I meant something like writing a short description of each function above them as comments, and creating doc pages out of them. I'm not sure if tools like Doxygen work on CL environment, or if there's any other tool with the same functionality.

**Comment by Shinmera** [comment]
Writing descriptions for functions *is* writing documentation.

**Comment by Borderliner** [comment]
Got it. Please leave this issue open, until you think the project is mature enough to be documented.

**Comment by stacksmith** [comment]
OK, how about a 'getting started'? Just getting it to quickload is an ordeal (for those of us who don't know what we are doing, needless to say)...

**Comment by Shinmera** [comment]
? What about getting it to load is a problem?

**Comment by stacksmith** [comment]
Aside from not knowing what to do with it when it does load (a simple demo is always nice, even if it's "hello world" in a window - at least it gives you an idea of the intended gross usage pattern), I encountered a some dependencies that required finding and pulling obscure repos from github.  It's all a blur as I spent the whole day trying different things, but I think... some missing linux library that I had to find.  Yes, I should've taken notes, but that would make my ADD feel left out.  
Anyway, please do not take this as anything other than a friendly suggestion from a fan.  I judge books by their cover, invest all-in on a hunch, trust initial impressions, and really love to get a library that may be helpful up into a demo mode so I can get a sense if I can use it or not.  Not being able to smoothly get some kind of a sign of life in 5 minutes gives me a pretty good signal about usability - not that you should give a *&$% about me using it.

**Comment by Shinmera** [comment]
Fwiw the current `workbench.lisp` shows a very simple sample scene which you should be able to run on latest quicklisp with just `(ql:quickload :trial-workbench) (workbench:launch)`.

**Comment by Shinmera** [comment]
The jam game we made recently is open source and can serve as another example: https://github.com/Shinmera/vpetjam

**Comment by JoeAnonymous** [comment]
Late Bumping this thread to say that vpetjam requires a package that doesn't seem to exist both on github or quicklisp, and therefore the workbench package is the only way for someone to tinker with it. The package is sdf/bmfont

And here's a personal complaint, when I try and run quickload or load-system, it claims it is unable to compile both the "trial" and "toolkit" source files. Unless of course, this is a recent issue. I did clear out the files and reinstalled them.

**Comment by Shinmera** [comment]
The sdf/bmfont system is in https://github.com/3b/sdf on branch `msdf` and `rewrite`.

It is very likely that trial has drifted from the API vpetjam was written against, hence the issues in the source files you mention. The API instability is a large reason I haven't committed to documenting things yet, since I just don't have the resources on hand to both work on Kandria and keep everything else updated as well.

Once I get to Kandria's source release I'll invest some time into a custom dist that should ship everything needed out of the box, as well as at least some high level documentation stuff that shouldn't change drastically any time soon.

**Comment by JoeAnonymous** [comment]
I should've double checked my writing. When I say the source files, I'm referring to trail's files, not vpetjam.
Apologies.

**Comment by Shinmera** [comment]
There's no `trial` source file in Trial, and everything compiles just fine.

**Comment by JoeAnonymous** [comment]
I'm running this under doom emacs.
quickloading or running load-system with :trial by itself gives me this error.

> COMPILE-FILE-ERROR while
> compiling #<CL-SOURCE-FILE "trial" "toolkit">
>    [Condition of type UIOP/LISP-BUILD:COMPILE-FILE-ERROR]

**Comment by Shinmera** [comment]
That doesn't actually tell me what it's chocking on. You'll need the output from the REPL.

**Comment by JoeAnonymous** [comment]
OK. here is what the REPL gave me.

> To load "trial":
>   Load 1 ASDF system:
>     trial
> ; Loading "trial"
> ..................
> ; 
> ; caught ERROR:
> ;   READ error during COMPILE-FILE:
> ;   
> ;     Symbol "PARSE-NATIVE-NAMESTRING" not found in the PATHNAME-UTILS package.
> ;   
> ;       Line: 362, Column: 64, File-Position: 12926
> ;   
> ;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/anon/common-lisp/trial/toolkit.lisp" {10060C3B23}>
> ; Debugger entered on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1004A3AFB3}>

**Comment by JoeAnonymous** [comment]
UPDATE:
i just realized that the pathname-utils that exists in quicklisp isn't the same as the one on github.
cloning the repository worked now.

Fingers crossed that it is the only problem.

**Comment by Shinmera** [comment]
Yeah, Quicklisp hasn't updated yet to pull in the patches from pathname-utils.

**Comment by JoeAnonymous** [comment]
OK, so even with that working, workbench:launch crashes.

> 2022-09-05 19:36:38 [INFO ] <TRIAL.MAIN>: GENESIS
> 2022-09-05 19:36:38 [INFO ] <TRAIL.MAIN>: Launching version 1.2.0-64a1229
> 2022-09-05 19:36:38 [INFO ] <TRIAL.BACKEND.GLFW>: Creating context #<CONTEXT {1006A4C973}>
> 2022-09-05 19:36:38 [INFO ] <TRIAL.CONTEXT>: Recreated context successfully.
> ; Debugger entered on #<SB-INT:SIMPLE-CONTROL-ERROR "A function with declared result type NIL returned:
> ;   ~S" {10073656D3}>

**Comment by Shinmera** [comment]
I believe that's an SBCL bug. What version are you on?

**Comment by JoeAnonymous** [comment]
2.1.11 debian

**Comment by Shinmera** [comment]
Yep, that's the one. It was fixed in the version immediately after, 2.2.0.

**Comment by JoeAnonymous** [comment]
I see, thank you for your time. Hopefully it doesn't get worse.

**Comment by Shinmera** [comment]
It definitely works on 2.2.1 and 2.2.8 (latest). I assume 2.2.x in general is fine.

**Comment by JoeAnonymous** [comment]
Building on my only issue I sent. I wonder if its necessary to write down all the required libraries that one may need. Or since its already pretty close to Kandria's release, if that's even needed, assuming that Trial will be 'completed' before then.

Unless i'm the only one having problems.

**Comment by Shinmera** [comment]
As far as I know you're the only one aside from the dev team trying to use trial at this time.

**Comment by Shinmera** [comment]
I've started documenting things now. It'll take a while for it to get filled out, though: https://shirakumo.github.io/trial/?a=b

**Comment by Shinmera** [comment]
Installing Trial and other projects like it should now be much easier if you use the Shirakumo dist: https://dist.shirakumo.org/shirakumo/

It ships all the dependencies needed that may drift from the base quicklisp dist.

**Comment by Shinmera** [comment]
https://shirakumo.github.io/trial/start.html
