### ISSUE TITLE
Trying to (ql:quickload :trial-workbench)

### ISSUE THREAD

**Issue by kozodev** [Shirakumo/trial#27]
Greetings,

FIrst off: I want to say thank you for the work you've put in to making this engine. I hope the best for you with Kandria.

Thank you!

To load "trial-workbench":
  Load 1 ASDF system:
    trial-workbench
; Loading "trial-workbench"
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "CALL-WITH-DEVICES" not found in the ORG.SHIRAKUMO.FRAF.GAMEPAD package.
;   
;       Line: 57, Column: 32, File-Position: 2543
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/guix/quicklisp/local-projects/trial-master/gamepad.lisp" {100193A1F3}>
While evaluating the form starting at line 10, column 0

**Comment by Shinmera** [comment]
Get cl-gamepad from git.

**Comment by kozodev** [comment]
Thank you!
