### ISSUE TITLE
When loading (workbench:launch)

### ISSUE THREAD

**Issue by kozodev** [Shirakumo/trial#28]
I looked through some of your .lisp files, not sure where it's trying to load this. Thanks again for your help.

Component "findapet" not found
   [Condition of type ASDF/FIND-COMPONENT:MISSING-COMPONENT]

Restarts:
 0: [RETRY] Retry ASDF operation.
 1: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 2: [RETRY] Retry SLY mREPL evaluation request.
 3: [*ABORT] Return to SLY's top level.
 4: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {100238DCD3}>)

Backtrace:
 0: ((LAMBDA NIL :IN ASDF/SYSTEM:FIND-SYSTEM))
 1: (ASDF/SESSION:CONSULT-ASDF-CACHE (ASDF/SYSTEM:FIND-SYSTEM "findapet") #<FUNCTION (LAMBDA NIL :IN ASDF/SYSTEM:FIND-SYSTEM) {10042F9E8B}>)
      Locals:
        KEY = (ASDF/SYSTEM:FIND-SYSTEM "findapet")
        THUNK = #<FUNCTION (LAMBDA () :IN ASDF/SYSTEM:FIND-SYSTEM) {10042F9E8B}>
 2: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/SYSTEM:FIND-SYSTEM) {10042F9E8B}> :OVERRIDE NIL :KEY (ASDF/SYSTEM:FIND-SYSTEM "findapet") :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL..
      Locals:
        FUN = #<FUNCTION (LAMBDA () :IN ASDF/SESSION:CALL-WITH-ASDF-SESSION) {10042F9ECB}>
        KEY = (ASDF/SYSTEM:FIND-SYSTEM "findapet")
        OVERRIDE = NIL
        OVERRIDE-CACHE = NIL
        OVERRIDE-FORCING = NIL
        THUNK = #<FUNCTION (LAMBDA () :IN ASDF/SYSTEM:FIND-SYSTEM) {10042F9E8B}>
 3: ((:METHOD TRIAL:VERSION ((EQL :APP))) #<unused argument>) [fast-method]
 4: ((LAMBDA NIL :IN TRIAL:LAUNCH))
 5: (DISSECT::STACK-CAPPER #<FUNCTION (LAMBDA NIL :IN TRIAL:LAUNCH) {534EA57B}>)
 6: (TRIAL:LAUNCH WORKBENCH:WORKBENCH)
 7: (SB-INT:SIMPLE-EVAL-IN-LEXENV (WORKBENCH:LAUNCH) #<NULL-LEXENV>)
 8: (EVAL (WORKBENCH:LAUNCH))
 9: ((LAMBDA NIL :IN SLYNK-MREPL::MREPL-EVAL-1))

**Comment by Shinmera** [comment]
Sorry about that. Been going a bit loose with the changes in the past three days rushing with the Eternia release.

**Comment by kozodev** [comment]
No worries, I'll hold off for awhile. Thanks for the quick reply.

**Comment by Shinmera** [comment]
Nah, should work fine now.
