### ISSUE TITLE
What are your thoughts on an RPG or ARPG?

### ISSUE THREAD

**Issue by Zavoka** [Shirakumo/trial#29]
Hello,

Do you feel Trial would handle making a Diablo style game with multiplayer?

With renewed interest from the lisp game jam, I went looking through tools again for game making and would like to use Trial. A big factor is that you've made it modular.

Thank you for your time

**Comment by Shinmera** [comment]
I don't see why not. There's currently no multiplayer systems built-in, so you'd have to manage all of that yourself, though.

**Comment by Zavoka** [comment]
Alright, sounds good.
