### ISSUE TITLE
workbench:launch doesn't *completely* work.

### ISSUE THREAD

**Issue by JoeAnonymous** [Shirakumo/trial#30]
The workbench test itself loads and the fps counter moves, but it also signals an error that there is an unknown key argument is called in poll-events, which is called by poll-input.

> Unknown &KEY argument: :FUNCTION
>    [Condition of type UNKNOWN-KEYWORD-ARGUMENT]
> Backtrace:
>  0: (ORG.SHIRAKUMO.FRAF.GAMEPAD:POLL-DEVICES :FUNCTION #<FUNCTION (LAMBDA (TRIAL:ACTION TRIAL:DEVICE) :IN TRIAL:POLL-INPUT) {100165C9BB}>) [more]
>  1: ((:METHOD TRIAL:POLL-INPUT :AFTER (TRIAL::GAMEPAD-INPUT-HANDLER)) #<WORKBENCH:WORKBENCH {10055EE913}>) [fast-method]
>  2: ((SB-PCL::EMF TRIAL:POLL-INPUT) #<unused argument> #<unused argument> #<WORKBENCH:WORKBENCH {10055EE913}>)
>  3: (TRIAL:LAUNCH-WITH-CONTEXT #<unavailable argument> #<unavailable &MORE argument>)
>  4: ((FLET TRIAL::THUNK :IN TRIAL:LAUNCH))
>  5: (TRIAL:LAUNCH WORKBENCH:WORKBENCH)
>  6: (SB-INT:SIMPLE-EVAL-IN-LEXENV (WORKBENCH:LAUNCH) #<NULL-LEXENV>)
>  7: (EVAL (WORKBENCH:LAUNCH))
>  8: ((LAMBDA NIL :IN SLYNK-MREPL::MREPL-EVAL-1))

Going through the source code, the only thing poll-events asks for is a timeout key. but is instead passed a lambda function.

**Comment by Shinmera** [comment]
You need a more recent version of [cl-gamepad](https://github.com/shirakumo/cl-gamepad).
