### ISSUE TITLE
Please, move data/masko-naive to a separate git repository and ASDF system

### ISSUE THREAD

**Issue by svetlyak40wt** [Shirakumo/trial#34]
This folder was changed 4 years ago, but because of it each new build of Trial results in 40M archive. Trial updates relatively frequently and each update generate this 40M archive [at Ultralisp.org](https://ultralisp.org/projects/Shirakumo/trial).

This also makes user wait longer when downloading updated asdf system.

**Comment by Shinmera** [comment]
Dang, I never even realised that that would be an issue. Sorry about that! The files have been moved to https://github.com/shirakumo/trial-assets
