### ISSUE TITLE
A few questions about portability

### ISSUE THREAD

**Issue by bohonghuang** [Shirakumo/trial#40]
Hi! I'm fond of the design and development experience of Trial and trying to use it for cross-platform game development in Lisp. But knowing that Trial is majorly tested to run with SBCL on Windows/MacOS/Linux, I'm curious about the portability of my game. Does Trial depend on some SBCL-specific features (including the high performance) or the packages that only compile in SBCL? How difficult is it to compile Trial in other Lisp implementations like ECL, making Trial run on the platforms like Android/iOS/Web in the future? Thanks in advance.

**Comment by Shinmera** [comment]
No idea. You'll have to find out the hard way.

**Comment by bohonghuang** [comment]
Alright. It looks like I may need to sacrifice some portability to go with Trial. Thank you for your response.

**Comment by bohonghuang** [comment]
So portability is currently not Trial's short-term goal, right? Could you please provide some insights on what is currently preventing Trial from being portable?

**Comment by Shinmera** [comment]
Developer time

**Comment by bohonghuang** [comment]
I understand, and thank you for all that you have done so far. It's already great.
