### ISSUE TITLE
System "lru-cache" not found

### ISSUE THREAD

**Issue by leafbebop** [Shirakumo/trial#46]
Hi, I want to try out this project, and see the comment https://github.com/Shirakumo/trial/issues/21#issuecomment-1271314047 here, and use the dist mentioned.
However, `(ql:quickload :trial)` gives the error:
`System "lru-cache" not found`

I tried looking through the repo and indeed can't find the system.

**Comment by Shinmera** [comment]
It does now.

**Comment by leafbebop** [comment]
Thanks for that. However I am encountering another problem:
when compiling `#<CL-SOURCE-FILE "mmap" "windows">`, I got the error:
```
 debugger invoked on a SB-INT:BUG in thread
#<THREAD "main thread" RUNNING {1000228113}>:
    full call to SB-C::UNSIGNED+SIGNED
```

I'm on sbcl-2.3.2 on windows 10. Is this a bug of sbcl itself?

**Comment by Shinmera** [comment]
yeah, you have to update.
