### ISSUE TITLE
Issues getting started on an M2 mac.

### ISSUE THREAD

**Issue by olaven** [Shirakumo/trial#53]
Dear @shirakumo, 

Thank you for creating this. I am learning Common Lisp and want to make a simple game with Trial. However, I have been struggeling with getting something up and running. I have set up a project similar to the one in the [start guilde](https://shirakumo.github.io/trial/start.html). However, when I try to load the project in the REPL, it fails when loading the `trial-glfw`-library. I get similar errors when trying to use the other backends [listed here](https://github.com/Shirakumo/trial/tree/master/backends). 

```
* (ql:quickload :gamejam)
To load "gamejam":
  Load 1 ASDF system:
    gamejam
; Loading "gamejam"
................................
debugger invoked on a LOAD-FOREIGN-LIBRARY-ERROR in thread
#<THREAD "main thread" RUNNING {70062604A3}>:
  Unable to load any of the alternatives:
   ("libglfw3.1.dylib" "libglfw3.dylib" "libglfw.3.1.dylib" "libglfw.3.dylib")
```

I have very little experience with game/graphics programming, but I thought maybe it could be related to me running an M2 mac. `trial-glop` fails with "architecture not supported", for instance. As mentioned, CL and its developer tools are new to me, so I might be misunderstanding something. 

Do you know what might be going wrong and what I can do to avoid it? :) 
Anyways, thank you for taking the time to read this! 

olaven.

**Comment by Shinmera** [comment]
You'll need to install glfw through brew or whatever, as `cl-glfw3` does not ship it.

In general Mac support is currently lacking. I'm the only real maintainer active on the project, and I do not have access to mac machines, let alone the more recent M1/M2s, (nor any patience for Apple's horseshit, fwiw). There's also so far not been any outside contributors that have ensured it to work properly on Apple's platforms, so you may encounter many more issues than this.

**Comment by olaven** [comment]
I see. Thank you very much for the quick and informative response.
