### ISSUE TITLE
Gltf asset doesn't generate resource

### ISSUE THREAD

**Issue by hpoggie** [Shirakumo/trial#60]
I exported the default cube from Blender as a gltf and tried to load it, but for some reason it doesn't seem to generate the resource. I'm not sure if this is a bug or if I'm just doing something dumb.

```
;;;; minimal-repro.lisp

(in-package #:minimal-repro)

(define-pool foo)

(define-asset (foo cube) org.shirakumo.fraf.trial.gltf:asset
    #p"cube.gltf")

(defclass main (trial:main)
  ())

(defun launch (&rest args)
  (apply #'trial:launch 'main args))

(defmethod setup-scene ((main main) scene)
  ;;(enter (make-instance 'vertex-entity :vertex-array (// 'trial 'unit-cube)) scene)
  (enter (make-instance 'vertex-entity :vertex-array (// 'foo 'cube)) scene)
  (enter (make-instance '3d-camera :location (vec 0 0 -3)) scene)
  (enter (make-instance 'render-pass) scene))
```

Doing `(minimal-repro:launch)` gives the error

```
Loading the asset
  #<ASSET FOO/CUBE>
did not generate the resource
  #<PLACEHOLDER-RESOURCE FOO/CUBE[T]>
   [Condition of type SIMPLE-ERROR]
```

Zip with the code and gltf file in it:
[minimal-repro.zip](https://github.com/Shirakumo/trial/files/13222296/minimal-repro.zip)

**Comment by Shinmera** [comment]
The asset doesn't produce one canonical mesh resource, since the gltf file can contain an arbitrary number of them. You have to address the specific mesh you want from the file by its name in the file, eg ``(// 'foo 'cube "Cube")`` or whatever it is in actuality.

**Comment by hpoggie** [comment]
Ah, that makes sense. Thanks!

**Comment by Shinmera** [comment]
Also please note that on current master, the use of the gltf specific asset is no longer correct, and the generic ``model-file`` asset class should be used instead.
