### ISSUE TITLE
hide-cursor fails with error on GLFW

### ISSUE THREAD

**Issue by hpoggie** [Shirakumo/trial#61]
According to [https://shirakumo.github.io/trial/context.html](https://shirakumo.github.io/trial/context.html) I can do

```
(hide-cursor *context*)
```

to hide the OS cursor, but this produces the error

```
:HIDDEN is not defined as a keyword for enum type #<CFFI::FOREIGN-ENUM ORG.SHIRAKUMO.FRAF.GLFW.CFFI:FLAG>.
   [Condition of type SIMPLE-ERROR]
```

Doing

```
(setf (org.shirakumo.fraf.glfw:input-mode :cursor *context*) :cursor-hidden))
```
seems to work fine. It seems like the actual flag is called GLFW_CURSOR_HIDDDEN according to [this](https://www.glfw.org/docs/latest/input_guide.html) so I don't know why it's just passing `:hidden`.

**Comment by Shinmera** [comment]
Because it's an oversight from when we used a different library for glfw.
