### ISSUE TITLE
ql:quickload stuck on 'trial and 'trial-examples

### ISSUE THREAD

**Issue by Ecsodikas** [Shirakumo/trial#64]
I've installed the `(ql-dist:install-dist "http://dist.shirakumo.org/shirakumo.txt")` repository and afterwards i ran `(ql:quickload 'trial)` and `(ql:quickload 'trial-examples)` but both just hand after a few seconds like this:

![image](https://github.com/Shirakumo/trial/assets/19648183/f5dde9d4-cd47-41b8-8476-d0c363103123)

It seems like nothing is happening, I've let it run for ~30 minutes and I've got no response. Sadly there is no error or something else to narrow down the problem. I'm using spacemacs with sly and the latest SBCL version 2.3.11.

Any help is appreciated.

**Comment by Shinmera** [comment]
Your sbcl probably ran out of memory, check your inferior-lisp buffer. Make sure to start sbcl with at least 2GB of dynamic space size.

**Comment by Ecsodikas** [comment]
That was it. Thanks for the super fast answer!
