### ISSUE TITLE
Error compiling #<CL-SOURCE-FILE "mmap" "windows">

### ISSUE THREAD

**Issue by sorumehta** [Shirakumo/trial#72]
After doing (ql:quickload :trial) in slime, I got the following error during the compilation stage:
[package mmap]....

The error message:

full call to SB-C::UNSIGNED+SIGNED
This is probably a bug in SBCL itself. (Alternatively, SBCL
might have been corrupted by bad user code, e.g. by an undefined
Lisp operation like (FMAKUNBOUND 'COMPILE), or by stray pointers
from alien code or from unsafe Lisp code
 [Condition of type SB-INT:BUG]

SBCL Version: 2.3.2
OS: Windows 11 
Architecture: AMD64

**Comment by Shinmera** [comment]
This error is not from trial, please report in the correct repositories.

Also your SBCL version is too old, you have to update.
