### ISSUE TITLE
CFFI does not load opengl libraries on fedora linux on mac

### ISSUE THREAD

**Issue by sorumehta** [Shirakumo/trial#73]
I am using Asahi Fedora Linux on a Mac (Apple Silicon). The OS claims to support OpenGL 3. I have all the opengl libraries installed, and I can get the "getting started" example on [glfw website](https://www.glfw.org/docs/3.0/quick.html) to work on this platform successfully (although I installed glfw and its dependencies for C after I installed trial using quicklisp, is that a problem? I did uninstall trial and installed it again, but still no luck).

After building trial, When I do (org.my.project:launch), I get the following error from CFFI:

Backtrace:
  0: (CFFI::FL-ERROR "Unable to load any of the alternatives:~%   ~S" NIL)
  1: ((FLET CFFI::%DO-LOAD :IN CFFI::%DO-LOAD-FOREIGN-LIBRARY) #<CFFI:FOREIGN-LIBRARY LIBGLFW> ORG.SHIRAKUMO.FRAF.GLFW.CFFI:LIBGLFW (:OR))
  2: (CFFI:LOAD-FOREIGN-LIBRARY ORG.SHIRAKUMO.FRAF.GLFW.CFFI:LIBGLFW :SEARCH-PATH NIL)
  3: (CFFI:LOAD-FOREIGN-LIBRARY ORG.SHIRAKUMO.FRAF.GLFW.CFFI:LIBGLFW :SEARCH-PATH NIL)
  4: (ORG.SHIRAKUMO.FRAF.GLFW:INIT)

For more context, this is how I compiled the "getting started" glfw program, which worked:
`g++ main.o -o main.exec -lGL -lGLU -lglfw3 -lX11 -lXrandr -lpthread -lXi`

Looks like it did not find any libraries to load.
Can you please help me with this?

**Comment by Shinmera** [comment]
The order doesn't matter. But again, this is the wrong repository for this issue. The problem is in the [glfw wrapper](https://github.com/Shirakumo/glfw/) , which does not have precompiled arm64 binaries for linux. Please use the lib in the wrapper to compile and submit a PR with the generated library.

**Comment by Shinmera** [comment]
You should be able to just run `make` within the glfw/lib directory.

**Comment by sorumehta** [comment]
Thank you @Shinmera for the guidance. I tried to build it, but I ran into an issue. But I do understand this is the wrong repository to open this issue in. So I have [created the issue](https://github.com/Shirakumo/glfw/issues/8) in glfw repo instead, and closing this one. Would be helpful if you could take a look at that. Thanks!
