### ISSUE TITLE
"Symbol *GC-REAL-TIME* not found in the SB-EXT package." When trying to quickload Trial

### ISSUE THREAD

**Issue by awesomebjt** [Shirakumo/trial#74]
I have followed the getting started tutorial, but when I attempt to run `(ql:quickload :trial)` I always get this error. I'm pretty new to Common Lisp so I don't understand what I'm looking at. Neither Google nor ChatGPT have been helpful on this one. There don't seem to be any issues or documentation for SB-EXT that ever mention anything called GC-REAL-TIME. Could this be a bug in Trial? Maybe there's an unmentioned dependency that would add this entity to SB-EXT? Perhaps I've done something obviously wrong.

I am using SBCL, version 2.3.6 on Fedora Linux.

```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "*GC-REAL-TIME*" not found in the SB-EXT package.
;   
;       Line: 67, Column: 40, File-Position: 2234
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/bjt/.quicklisp/dists/shirakumo/software/machine-state-24c29f98ae9342510d2c3530e9788a4f5e3d2c5c/protocol.lisp" {10127B7343}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD tid=544317 "main thread" RUNNING {101B038183}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "machine-state" "protocol">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
```

If I enter `HELP` and use the backtrace and list-locals features in the debugger, I see these:
```
BACKTRACE 3

Backtrace for: #<SB-THREAD:THREAD tid=547495 "main thread" RUNNING {101B038183}>
0: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "machine-state" "protocol">)))
1: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "machine-state" "protocol">)
2: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))

0] LIST-LOCALS
UIOP/LISP-BUILD::CONTEXT-ARGUMENTS  =  ((#<ASDF/LISP-ACTION:COMPILE-OP >
                                            . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "machine-state" "protocol">))
UIOP/LISP-BUILD::CONTEXT-FORMAT  =  "~/asdf-action::format-action/"
UIOP/LISP-BUILD::FAILURE-P  =  T
UIOP/LISP-BUILD::OUTPUT  =  NIL
UIOP/LISP-BUILD::WARNINGS-P  =  T
```

**Comment by awesomebjt** [comment]
It looks like the same thing happens if I try to install using `ocicl` instead with `ocicl install trial`

**Comment by Shinmera** [comment]
As can be seen from the trace this is *not* a problem with trial, but with machine-state:

> /home/bjt/.quicklisp/dists/shirakumo/software/machine-state-24c29f98ae9342510d2c3530e9788a4f5e3d2c5c/

As for the actual issue, your SBCL is too old.

**Comment by no-defun-allowed** [comment]
> Neither Google nor ChatGPT have been helpful on this one.

The parallel GC was upstreamed after the GPT4 knowledge cutoff date, so the latter is not surprising. The former is my bad; it should be in the SBCL manual but I didn't get around to documenting it there.

> Maybe there's an unmentioned dependency that would add this entity to SB-EXT?

SBCL 2.3.7 or newer.

**Comment by awesomebjt** [comment]
Thanks. An out of date SBCL was the issue (installed from the Fedora repos). I got the latest, and it's running fine now.
