### ISSUE TITLE
Scaffold generation tool

### ISSUE THREAD

**Issue by Ytrog** [Shirakumo/trial#77]
I saw in the [getting started](https://shirakumo.github.io/trial/start.html) tutorial about how to do project scaffolding. Maybe it would be nice to have a tool that generates the nescessary files for you. 🤔

**Comment by Shinmera** [comment]
There's plenty of other things out there like quickproject that do that kinda thing. Compared to making a game, writing an ASD and a package file takes no time at all, so I see no point in doing this.

**Comment by Ytrog** [comment]
Understandable.
