### ISSUE TITLE
Find a Suitable Sound System

### ISSUE THREAD

**Issue by Shinmera** [Shirakumo/trial#8]
Qt's included sound capabilities are either complete crap (QSound) or deprecated (Phonon). We might have to either use Phonon after all or find some third-party solution like gstreamer, for which bindings need to be written first.

**Comment by Shinmera** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;WL0hOgL3&#x2F;1-audio-system"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Audio system</a>

**Comment by borodust** [comment]
[cl-openal](https://github.com/zkat/cl-openal) will probably do

**Comment by Shinmera** [comment]
Iirc OpenAL does not have the mixing capabilities I need and doesn't handle source formats at all.

**Comment by Shinmera** [comment]
To elaborate: OpenAL is probably the right backend to use, but there's a lot more additional machinery that needs to be in place for it to become truly useful.

**Comment by Shinmera** [comment]
We now have Harmony to use for this.
