### ISSUE TITLE
Movie support?

### ISSUE THREAD

**Issue by kflak** [Shirakumo/trial#82]
Hi,

Looking into finding a good cl-replacement for openFrameworks, but the big obstacle these days is the support for playing back and manipulating movie files. Is this possible or even plausible within the trial framework?

**Comment by Shinmera** [comment]
Trial only supports playing back Theora files. If you're looking for video codec and manipulation, this is not the place.

**Comment by kflak** [comment]
Ok, thanks for the quick response!
