### ISSUE TITLE
Unable to play sounds via `(// 'my-project 'my-sound)` pattern

### ISSUE THREAD

**Issue by fosskers** [Shirakumo/trial#83]
While going through the Audio section of the guide, I'm able to play sounds without issue in forms like:

```lisp
(harmony:play
 #p"/home/colin/code/common-lisp/save-the-farm/data/meow.mp3")
```
but seem unable to do:
```lisp
(harmony:play (// 'farm 'meow))
```
as advertised in the guide. This occurs in top-level send-to-repl experiments and also in my Trial handlers. I've referenced the Kandria source, and as far as I can tell I'm defining my sound assets in the same way as it. Example:
```lisp
(define-asset (farm meow) trial-harmony:sound
    #p"meow.mp3")
```
One things that Kandria seems to be doing that I'm not is "staging" the sounds (https://github.com/Shirakumo/kandria/blob/383eb40e0853f20f79bae2b99eeb9fcfd0b38e91/rope.lisp#L20-L22), although I'm not sure that that's necessary for me as the Guide doesn't mention it.

Thanks to the `define-asset` and `//` macros, I know that if I try to define or reference an asset file that doesn't exist, a condition will be thrown immediately. So, Trial can see my MP3. But when I actually call `play`, I'm told:
```
No such segment #<PLACEHOLDER-RESOURCE FARM/MEOW[T]>
```
which is raised within `harmony:segment`.

I had also tried defining the assets via `define-assets-from-path` as in [this Kandria code](https://github.com/Shirakumo/kandria/blob/383eb40e0853f20f79bae2b99eeb9fcfd0b38e91/assets.lisp#L137), but the result was the same.

### Leads
- Through debugging, I notice it dispatching to the `T` variant of `harmony:play`, not the `voice` variant as defined in `trial-harmony`. Is a `sound` a `voice`? The line in the guide `Note that each asset generates exactly one voice instance.` implies yes, but the class hierarchy of `sound` says no.
- I haven't yet tried with a file other than an MP3.
- Kandria uses a further `define-track` macro wrapper around `define-assets` which sets many more keyword val pairs. Perhaps I'm missing something?

### Context
- Shirakumo dist `2024.08.16-07.28.33`

Thanks again for any input you can offer.

**Comment by Shinmera** [comment]
You do have to stage any resource that you will make use of. Kandria does do this, though it's spread all over the code base.

**Comment by fosskers** [comment]
> any resource

Images seem to "just work" without explicit staging, yeah?

**Comment by fosskers** [comment]
This seems to do it:
```lisp
(defmethod stage :after ((jack my-cube) (area staging-area))
  (stage (// 'farm 'meow) area))
```

**Comment by Shinmera** [comment]
If you're using a textured-entity, then that entity stages the resource for you. There is no way for the entity to know about your sound, though, so it cannot do the same for sounds.

**Comment by fosskers** [comment]
Thanks!
