### ISSUE TITLE
Runnable Tilemap / Sprite examples?

### ISSUE THREAD

**Issue by fosskers** [Shirakumo/trial#85]
The wolf sprite example defined like so:
```lisp
(define-example sprite
  :title "Animated Sprites"
  (enter (make-instance 'simple-sprite :sprite-data (assets:asset :wolf) :name :sprite) scene)
  (enter (make-instance 'sidescroll-camera :zoom 10.0 :target (node :sprite scene)) scene)
  (enter (make-instance 'render-pass) scene))
```
unfortunately doesn't compile, due to `assets` not existing. The `cat.png` asset exists in `data/`, and I was wondering if `:wolf` (and also the `:tilemap` from `tilemap.lisp`) used to also be included somewhere. 

For now I'll follow the [Sprites page](https://shirakumo.github.io/trial/sprites.html) directly. 

Thanks again.

**Comment by Shinmera** [comment]
? it sure does compile, what are you talking about.

**Comment by fosskers** [comment]
It doesn't seem to compile on my end, nor is there any filename with "wolf" in it in the repo. Is something perhaps unpushed?

I also tried `(// 'trial 'wolf)`, but that didn't seem to work either. What am I overlooking here?

**Comment by fosskers** [comment]
Ah seems like in general, sprites need to be called via `asset`, not `//`.

**Comment by compufox** [comment]
I think you’re missing trial-assets: https://github.com/Shirakumo/trial-assets

**Comment by fosskers** [comment]
That would be it, thanks!

**Comment by Shinmera** [comment]
The examples use their own package, which has its own nicknames and macros and everything. Why would you assume you can just copy-paste code willy-nilly into a different environment and have it work?

**Comment by fosskers** [comment]
> Why would you assume you can just copy-paste code willy-nilly into a different environment and have it work?

To clarify, I was attempting:

```
(enter (make-instance 'simple-sprite :sprite-data (assets:asset :wolf) :name :sprite) scene)
```
in my own `setup-scene`. I had assumed it would work because using `cat.png` had worked in the Quickstart guide, and I thought the Examples would function in the same way. That was wrong, because I was unaware that the examples were bundled separately by you here.

**Comment by Shinmera** [comment]
Trial's own asset function takes two args and comes from the trial package. This is an asset function that takes one argument and comes from a different package altogether.

**Comment by fosskers** [comment]
Thanks for the clarification, I understand the difference now.

**Comment by Shinmera** [comment]
`//` returns a resource like a texture or a buffer. The sprite needs additional metadata to function, which is only present on the asset.
