### ISSUE TITLE
Squashed / corrupted sprites

### ISSUE THREAD

**Issue by fosskers** [Shirakumo/trial#87]
Hi again, I'm having some trouble loading sprites. As far as I know I've followed [the Guide](https://shirakumo.github.io/trial/sprites.html) to the letter, exporting an animated sprite from Asesprite whose subsequent JSON looks fine, yet when I run the program I see:
 
https://vimeo.com/1005219262

We can see at least something of the blue of his sword swing here. Similarly, an attempt to load a sprite with only 1 frame (a lemon) looks like:

![lemon](https://github.com/user-attachments/assets/65c48037-9e6e-4cdd-8d11-93745cb82606)

Meanwhile, [here is the original](https://github.com/fosskers/save-the-farm/blob/master/data/sprites/lemon.png).

I've done my best to debug this, but can't tell what's wrong. Have I...

- set up the camera wrong?
- exported the sprites wrong?
- somehow left out some other critical scene setting?
- not prayed to the rain gods enough?

The code is here: https://github.com/fosskers/save-the-farm and should run as-is provided you're on the branch from #86 . I made that PR in the first place in order to debug this. Thanks for any help you can offer.

**Comment by Shinmera** [comment]
Sprite packing seems to have broken in a regression. I'll take a look tomorrow.

**Comment by fosskers** [comment]
![a-lemon](https://github.com/user-attachments/assets/9153b37d-1900-4b12-afa4-244e0c08ed02)

Works like a charm! Thanks for the quick fix.
