### ISSUE TITLE
Two sprite animation findings

### ISSUE THREAD

**Issue by fosskers** [Shirakumo/trial#88]
Thanks for the fix the other day, my farmer appears and can move around the screen. This morning I've succeed in getting him to animate, but discovered two caveats not mentioned in the guide.

### Manually setting the animations

Given:
```lisp
(define-pool farm :base #p"../../data/")
(define-asset (farm farmer) sprite-data #p"sprites/farmer.json")

(define-shader-entity farmer (animated-sprite located-entity)
  ((sprite-data :initform (asset 'farm 'farmer))))
```
and the following in my `setup-scene`:
```lisp
(enter (make-instance 'farmer :name :farmer) scene)
```
Through the inspector I discovered that while the `animations` slot within the inner `sprite-data` is properly parsed and stored, the `animations` slot in the parent `farmer` class (inherited from `animated-sprite`) remains empty. Unless I do something like this then attempts to `play` directly on the `farmer` will raise a condition:
```lisp
(defmethod setup-scene :after ((main stf-main) scene)
  (let ((farmer (node :farmer scene)))
    (setf (animations farmer) (animations (sprite-data farmer))) ; this
    (play 'idle farmer))) ; works, thanks to the line above. Throws otherwise.
```
Have I overlooked something w.r.t. inheriting off of `animated-sprite`?

### Manual `call-next-method` on the farmer's handler

With the above, even though a call to `play` no longer throws, the farmer renders but seems stuck in his first frame. However, if I:
```lisp
(define-handler (farmer tick) ()
  ;; ... other logic ... 
  (call-next-method)) ; this
```
then the `(defmethod handle ((ev tick) (sprite animated-sprite))` from Trial's `sprite.lisp` will actual be called, and the farmer will animate. Is there a more idiomatic way to do this? `define-handler` doesn't seem to support `:before` / `:after`.

Thanks again.

**Comment by Shinmera** [comment]
The animations are not yet loaded when you setup the scene, so you can't play anything, it doesn't know the animations, after all. Your setf working is only by accident. You can see the load logic in the `observe-load-state` method for the animated sprite.

As for define-handler, just look at its signature, c'mon: `(define-handler (class event &rest qualifiers) slots &body body)`
`qualifiers` are method qualifiers.

**Comment by Shinmera** [comment]
Usually it isn't necessary to do anything in the load observer. You'll want to set the animation in your `tick` handler based on the state of your entity. For instance in Kandria except for combat animations, all other animations are set in a `tick :after` handler: https://github.com/Shirakumo/kandria/blob/master/player.lisp#L1244

**Comment by fosskers** [comment]
Even `Idle`? While I hadn't tried it yet, I was concerned about the effect of calling `play` on every tick.

**Comment by Shinmera** [comment]
Sure why not. Play only does anything if the animation you're asking for is different.

**Comment by fosskers** [comment]
Confirmed:
1. The animations are loaded by the time I call `play` in my handler.
2. The handler indeed needs a `:before` in order for the parent's method of the same name to be automatically called (as expected).
3. I don't need to manually load the animations in a `setup-scene :after` as I had been doing.

Thanks again.
