### ISSUE TITLE
Error building on macOS 15.1 Beta (Apple Silicon)

### ISSUE THREAD

**Issue by AliceVie** [Shirakumo/trial#91]
```
➜  ~ sbcl --version
SBCL 2.4.8
```

When running `(ql:quickload :trial)` the following error occurs:
```
debugger invoked on a CFFI::FOREIGN-LIBRARY-UNDEFINED-ERROR in thread
#<THREAD tid=259 "main thread" RUNNING {7011E308A3}>:
  Undefined foreign library: ORG.SHIRAKUMO.MESSAGEBOX::FOUNDATION
```

I am able to accept the error and compilation completes with no further errors. I am also still able to use `org.shirakumo.messagebox:show` within my project without issue. This is likely low-priority, but still weird behavior. I'm posting this issue here rather than on the messagebox repo as I am able to `(ql:quickload :messagebox)` without any errors, it only seems to occur when compiling trial.

**Comment by Shinmera** [comment]
Sorry about that. Let me know if there's any other weirdness you encounter on mac. I don't have a mac system to test Trial with, so experience reports are very valuable.
